### ISSUE TITLE
Failing to Build

### ISSUE THREAD

**Issue by richardherbert** [TartanLlama/actions-eleventy#7]
I'm getting two issues when trying to build my site:

`Warning: Unexpected input(s) 'install_dependencies', valid inputs are ['entryPoint', 'args']`

and

`Eleventy requires Node 12. You will need to upgrade Node to use Eleventy!`

My action is simple:

```
name: Eleventy Build and Deploy
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.1
        with:
          args: --output _dist
          install_dependencies: true
```

What have I got wrong?
